// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogFrwtICeITe72TSSdPaJ-EY-T_mJYXQ',
    appId: '1:684234366954:web:189b3489c4f72f490d9c93',
    messagingSenderId: '684234366954',
    projectId: 'lost-and-found-2e3e1',
    authDomain: 'lost-and-found-2e3e1.firebaseapp.com',
    storageBucket: 'lost-and-found-2e3e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8at-QoEag9UuHYXtcnWwyxjNQbchFrdg',
    appId: '1:684234366954:android:6314fe7ff97cc8680d9c93',
    messagingSenderId: '684234366954',
    projectId: 'lost-and-found-2e3e1',
    storageBucket: 'lost-and-found-2e3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-Hd0v9OtBTKq4UXShkd9LAyNZNi_vzY',
    appId: '1:684234366954:ios:c11bf181de6258cb0d9c93',
    messagingSenderId: '684234366954',
    projectId: 'lost-and-found-2e3e1',
    storageBucket: 'lost-and-found-2e3e1.appspot.com',
    androidClientId: '684234366954-eump4inees74qtcqvc0s1om901tor71l.apps.googleusercontent.com',
    iosClientId: '684234366954-2p9mc9nsb3gl66r0mu3euqms2okfrt45.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc-Hd0v9OtBTKq4UXShkd9LAyNZNi_vzY',
    appId: '1:684234366954:ios:3219fc53e934084d0d9c93',
    messagingSenderId: '684234366954',
    projectId: 'lost-and-found-2e3e1',
    storageBucket: 'lost-and-found-2e3e1.appspot.com',
    androidClientId: '684234366954-eump4inees74qtcqvc0s1om901tor71l.apps.googleusercontent.com',
    iosClientId: '684234366954-oib2umsdb6dv91ndc6cke57pphipvae3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostAndFound.RunnerTests',
  );
}
